#!/usr/bin/env python3
"""
CEO Monday Morning Briefing Generator
Hackathon requirement: Weekly autonomous briefing
"""
import os, sys, json
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from secrets_config import load_secrets
load_secrets()

VAULT = Path(__file__).parent
NEEDS_ACTION = VAULT / 'Needs_Action'
DONE = VAULT / 'Done'
PENDING = VAULT / 'Pending_Approval'
BRIEFINGS = VAULT / 'CEO_Briefings'
BRIEFINGS.mkdir(exist_ok=True)

def generate_briefing():
    now = datetime.now()
    
    # Count files
    needs_action_count = len(list(NEEDS_ACTION.glob('*.md')))
    done_count = len(list(DONE.glob('*.md')))
    pending_count = len(list(PENDING.glob('*.md')))
    
    # Count by type
    email_done = len(list(DONE.glob('EMAIL_*.md')))
    whatsapp_done = len(list(DONE.glob('WHATSAPP_*.md')))
    batch_done = len(list(DONE.glob('BATCH_*.md')))
    
    # Read Business Goals
    goals_file = VAULT / 'Business_Goals.md'
    goals_content = goals_file.read_text(encoding='utf-8', errors='replace')[:500] if goals_file.exists() else 'No goals defined'
    
    briefing = f"""# Monday Morning CEO Briefing
**Generated:** {now.strftime('%Y-%m-%d %H:%M')}
**Period:** Weekly Autonomous Report

---

## Executive Summary
AI Employee is operational. Processing {done_count} completed tasks this week.

## Task Pipeline Status
| Folder | Count | Status |
|--------|-------|--------|
| Needs Action | {needs_action_count} | Pending Processing |
| Pending Approval | {pending_count} | Awaiting Human Review |
| Done | {done_count} | Completed |

## Completed Tasks Breakdown
- Emails Processed: {email_done}
- WhatsApp Messages: {whatsapp_done}
- Batch Processed: {batch_done}

## Business Goals Status
{goals_content}

## Bottlenecks
- {needs_action_count} items pending in Needs_Action since March 2026
- {pending_count} items awaiting human approval
- Action Required: Review Pending_Approval folder

## Proactive Suggestions
1. Run `python batch_processor.py --count 50` to clear backlog
2. Review {pending_count} pending approvals
3. Check Odoo for unpaid invoices at http://localhost:8069

## AI Employee Health
- Odoo: Running at http://localhost:8069
- Gmail API: Active (token valid)
- Docker: odoo_hackathon + odoo_postgres healthy
- DRY_RUN: false (real mode)

---
*Generated by AI Employee — Gold Tier*
*Vault: {VAULT}*
"""
    
    # Save briefing
    filename = f"{now.strftime('%Y-%m-%d')}_CEO_Briefing.md"
    briefing_file = BRIEFINGS / filename
    briefing_file.write_text(briefing, encoding='utf-8')
    print(f"CEO Briefing saved: {briefing_file}")
    print(f"Tasks: {needs_action_count} pending, {done_count} done, {pending_count} approvals")
    print("CEO BRIEFING GENERATED")
    return briefing_file

if __name__ == '__main__':
    generate_briefing()
